[package]
name = "aoc08"
version = "0.1.0"
authors = ["Said Aspen <mail@saidaspen.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
